version: "3.9"
services:
  postgres-taskforce:
    image: postgres:15.2
    container_name: taskforce-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: taskforce
    ports:
      - "5432:5432"
    volumes:
      - tfdata:/var/lib/postgresql/data

  postgres-prefect:
    image: postgres:15.2
    container_name: taskforce-prefectdb
    environment:
      - POSTGRES_USER=prefect
      - POSTGRES_PASSWORD=prefect_password
      - POSTGRES_DB=prefect
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: taskforce-redis
    restart: always
    ports:
      - "6379:6379"

  registry:
    image: registry:2
    container_name: taskforce-registry
    ports:
      - 5000:5000
    volumes:
      - registry_data:/var/lib/registry
  # server:
  #   image: prefecthq/server:latest
  #   container_name: taskforce-server
  #   environment:
  #     - POSTGRES_URL=postgres://prefect:prefect_password@taskforce-prefectdb:5433/prefect
  #     - DATABASE_URL=postgres://prefect:prefect_password@taskforce-prefectdb:5433/prefect
  #     - REDIS_URL=redis://redis:6379
  #     - PREFECT_SERVER__TELEMETRY__ENABLED=false
  #   ports:
  #     - "4200:4200"
  #   depends_on:
  #     - postgres-prefect
  #   restart: always

volumes:
  tfdata:
  postgres_data:
  registry_data:
  prefectdata:


networks:
  default:
    external:
      name: taskforce
